service: ${self:custom.project.name}
app: ${file(./serverless.js):project.app}
tenant: ${file(./serverless.js):project.tenant}

provider:
  name: aws
  stage: ${file(./serverless.js):provider.stage}
  stackName: ${file(./serverless.js):project.stackName}
  runtime: ${file(./serverless.js):provider.runtime}
  region: ${file(./serverless.js):provider.region}
  deploymentBucket:
    name: ${file(./serverless.js):provider.deploymentBucket.name}
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::ImportValue: ${file(./serverless.js):Imports.TableNameARN}
        - Fn::Join:
            - ''
            - - Fn::ImportValue: ${file(./serverless.js):Imports.TableNameARN}
              - '/*'

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  project: ${file(./serverless.js):project}

  webpack:
    packagePath: '../../package.json'
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'

functions:
  getHash:
    handler: functions/getHash/index.handler
    events:
      - http:
          path: hash
          method: post
          memorySize: 1024
          timeout: 5

  getStatByHash:
    handler: functions/getStatByHash/index.handler
    events:
      - http:
          path: stats/hash
          method: post
          memorySize: 3008
          timeout: 5

  getStatByUrl:
    handler: functions/getStatByUrl/index.handler
    events:
      - http:
          path: stats/url
          method: post
          memorySize: 3008
          timeout: 25

  getUrl:
    handler: functions/getUrl/index.handler
    events:
      - http:
          path: url
          method: get
          memorySize: 1024
          timeout: 100
