/* @flow */

'use strict';

const SPECIAL_SORT_KEY = 'SPECIAL';
const SPECIAL_HASH_KEY = '0000000';
const HASH_URL_SORT_KEY = 'DETAILS';
const HASH_TOATL_SORT_KEY = 'TOTAL';

module.exports = {
  SPECIAL_SORT_KEY,
  SPECIAL_HASH_KEY,
  HASH_URL_SORT_KEY,
  HASH_TOATL_SORT_KEY,
};
